device:
  # The default username and password of the system. Normally a plaintext password would be a security concern, however the
  # DART is isolated from the Internet and the password is meant to be common knowledge.
  # Also note there appear to be security requirements enabled that disallow this password being simpler. Note sure how to
  # disable.
  user1: zre
  user1pass: GoZipsFall2023!!

include:
  file: trixie-minbase-ab.yaml

image:
  # TODO(Barach): Resize this
  system_part_size: 2500M # Cage + wayland + chromium + deps
  name: dart_os

layer:
  device: dart-device
  software: zre-cantools
  splash: rpi-splash-screen
  dhcp: dhcp-server
  ssh: ssh-server

# TODO(Barach): Fill in path
zre_cantools:
  path: ./zre_cantools/

splash:
  image_path: ${@SRCROOT}/splash.tga